### PR TITLE
Remove multiple references to same library file

### PR DESCRIPTION
**Pull request by thundergnat**
Drastically slows down compilation as it recompiles the library for every mention of it in the provides section. It only needs to compile it once. 

see this comment (https://github.com/rakudo/rakudo/issues/4353#issuecomment-833513796

on[ Rakudo issue](https://github.com/rakudo/rakudo/issues/4353)

### CODE REVIEW

**Comment by ugexe** [comment]
Note changing just this probably isn't sufficient since other tools may e.g. `use TAP::Harness;` such as [zef](https://github.com/ugexe/zef/blob/602c54f1069631fd527473f4028451e5c47bc42c/lib/Zef/Service/TAP.rakumod#L71) and should be updated

**Comment by thundergnat** [comment]
Hmm. good point. Probably should change the entry point to TAP::Harness since that is how the module is referred to in the README, or maybe cut down the provides section to TAP and TAP::Harness. Two recompiles is still a lot better than twenty-six.

**Comment by Leont** [comment]
> Drastically slows down compilation as it recompiles the library for every mention of it in the provides section. It only needs to compile it once.

I had no idea about that, that does seem unfortunate (and unnecessary?)


I am sympathetic to this change, if only because mi6 doesn't support the current paradigm (it wants to overwrite it to what you're suggesting here) and that makes releasing the module a hassle. We would first have to deal with the ecosystem fallout though.

**Comment by Leont** [comment]
> Note changing just this probably isn't sufficient since other tools may e.g. use TAP::Harness; such as zef and should be updated

`prove6` and `mi6` use `TAP`, so if we just change zef we can remove `TAP::Harness` (and obviously all the other entries).

**Comment by Leont** [comment]
> > Note changing just this probably isn't sufficient since other tools may e.g. use TAP::Harness; such as zef and should be updated
> 
> `prove6` and `mi6` use `TAP`, so if we just change zef we can remove `TAP::Harness` (and obviously all the other entries). I don't think anything else uses this (though I might be mistaken).

It turns out zef's logic didn't work in the first place, so this is no longer a blocker.

**Comment by ugexe** [comment]
> It turns out zef's logic didn't work in the first place, so this is no longer a blocker.

It worked at one time, although I don't how long ago that actually was (presumably whenever the following still worked):
```
$ raku -e 'require TAP::Harness;'
P6M Merging GLOBAL symbols failed: duplicate definition of symbol Version
  in block <unit> at -e line 1
```

**Comment by ugexe** [comment]
```
➜  tap-harness6 git:(master) rakubrew switch moar-2019.03.1
Switching to moar-2019.03.1
➜  tap-harness6 git:(master) perl6 -I. -e 'require TAP::Harness;'

➜  tap-harness6 git:(master) rakubrew switch moar-2019.07.1
Switching to moar-2019.07.1
➜  tap-harness6 git:(master) perl6 -I. -e 'require TAP::Harness;'
P6M Merging GLOBAL symbols failed: duplicate definition of symbol Version
  in block <unit> at -e line 1
```

**Comment by Leont** [comment]
> > It turns out zef's logic didn't work in the first place, so this is no longer a blocker.
> 
> It worked at one time, although I don't how long ago that actually was (presumably whenever the following still worked):
> 
> ```
> $ raku -e 'require TAP::Harness;'
> P6M Merging GLOBAL symbols failed: duplicate definition of symbol Version
>   in block <unit> at -e line 1
> ```

That sounds like a rakudo bug to me. If `use` and `need` work, `require` should also work. `require ::('TAP')` also works fine, so it is an issue with the placeholder package.

**Pull request merged**
